name: probatio
title: probatio
version: '1.8.0'
summary: The all in one tool for everyones favoriete container tool
description: |
  Freeplane is a free and open source software application that supports
  thinking, sharing information and getting things done at work, in school
  and at home. The core of the software is tools for mind mapping (also known
  as concept mapping or information mapping) and using mapped information.

  Occupying the middle ground between an editor and a diagramming tool,
  Freeplane allows the user to add content as quickly and naturally as they
  would in a text editor, yet producing structured content that can be
  manipulated as easily as a diagram.

  Features include ordering ideas in nodes and freely positionable nodes,
  connecting nodes, automatic/conditional styles, scripting, add-ons, LaTeX,
  search/filtering, different export features, printing, password protection
  of nodes/maps and more.

grade: stable
confinement: strict
base: core18

website: https://github.com/BenCoepp/probatio
issues: https://github.com/BenCoepp/probatio/issues
license: MIT

apps:
  probatio:
    command: usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar $SNAP/probatio/target/probatio-1.0-SNAPSHOT.jar
    plugs: [ home, network]
    environment:
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA
parts:
  probatio:
    plugin: maven
    source: https://github.com/BenCoepp/probatio.git
    source-tag: main
    source-type: git
    maven-options:
      [ -DskipTests=true ]
    maven-targets:
      - probatio
    stage-packages:
      - openjdk-11-jre